title: Welcome 
description: A collection of thoughts
theme: minima

kramdown:
  math_engine: mathjax

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %B %Y"
#  skin: solarized-dark

# generate social links in footer#
social_links:
  twitter: jekyllrb
  github:  jekyll
  linkedin: jekyll
