title: Welcome 
description: A collection of thoughts
theme: minima

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %B %Y"
#  skin: solarized-dark

# generate social links in footer#
social_links:
  twitter: jekyllrb
  github:  jekyll
  linkedin: jekyll

kramdown:
  math_engine: mathjax

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

#plugins:
# - jekyll-feed
# - jekyll-seo-tag
